version: "3"
services:
  mongo:
    image: mongo 
    ports:
     - "27017:27017"
    volumes: 
        - 'cohabdata:/data/db'
  redis:
    image: redis
    volumes:
        - 'cohabdata:/data'
    ports:
        - '6379:6379'
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
  web:
    image: yilmazgunalp/cohab:0.1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - 'mongo' 
      - 'redis'
  nginx:
    image: yilmazgunalp/nginx:9.1
    ports:
      - '80:80'
      - '443:443'
    tty: true
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
    cohabdata:
