version: "3"
services:
  mongo:
    image: mongo 
    ports:
     - "27017:27017"
    volumes: 
        - 'cohabdata:/data/db'
  web:
    image: yilmazgunalp/cohab:0.1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - 'mongo' 
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
    cohabdata:
