version: '3'
services:
    web:
        build: .
        environment:
          - NODE_ENV
        volumes:
            - ".:/cohab"
        ports:
            - "3000:3000"
            - "4040:4040"
