version: '3'
services:
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
        depends_on:
            - 'web'
    web:
        image: "node"
        volumes:
            - ".:/cohab"
        ports:
            - "3000:3000"
        command: "npm start"
        working_dir: /cohab
