version: '3'
services:
    mongo:
        image: "mongo"
    redis:
        image: "redis"
    web:
        image: "yilmazgunalp/cohab:0.1"
        depends_on:
            - "mongo"
            - "redis"
