version: '3'
services:
    web:
        build: .
        ports:
            - "5000:3000"
        volumes:
            - .:/cohab
    mongo:
        image: "mongodb:latest"
    redis:
        image: "redis:latest"
